update=25.08.2018 11:18:22
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=TheONETXModule-rescue
LibName2=TheONETXParts
LibName3=C:/temp/DIY-Multiprotocol-TX-Module/PCB v2.3d/Multipro-txV2-3d-cache
LibName4=C:/Program Files/KiCad/share/kicad/library/modules
LibName5=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName6=C:/Program Files/KiCad/share/kicad/library/74xx
LibName7=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName8=C:/Program Files/KiCad/share/kicad/library/actel
LibName9=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName10=C:/Program Files/KiCad/share/kicad/library/allegro
LibName11=C:/Program Files/KiCad/share/kicad/library/Altera
LibName12=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName13=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName14=C:/Program Files/KiCad/share/kicad/library/atmel
LibName15=C:/Program Files/KiCad/share/kicad/library/audio
LibName16=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName17=C:/Program Files/KiCad/share/kicad/library/bbd
LibName18=C:/Program Files/KiCad/share/kicad/library/bosch
LibName19=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName20=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName21=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName22=C:/Program Files/KiCad/share/kicad/library/conn
LibName23=C:/Program Files/KiCad/share/kicad/library/contrib
LibName24=C:/Program Files/KiCad/share/kicad/library/cypress
LibName25=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName26=C:/Program Files/KiCad/share/kicad/library/device
LibName27=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName28=C:/Program Files/KiCad/share/kicad/library/diode
LibName29=C:/Program Files/KiCad/share/kicad/library/display
LibName30=C:/Program Files/KiCad/share/kicad/library/dsp
LibName31=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName32=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName33=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName34=C:/Program Files/KiCad/share/kicad/library/gennum
LibName35=C:/Program Files/KiCad/share/kicad/library/graphic_symbols
LibName36=C:/Program Files/KiCad/share/kicad/library/hc11
LibName37=C:/Program Files/KiCad/share/kicad/library/infineon
LibName38=C:/Program Files/KiCad/share/kicad/library/intel
LibName39=C:/Program Files/KiCad/share/kicad/library/interface
LibName40=C:/Program Files/KiCad/share/kicad/library/intersil
LibName41=C:/Program Files/KiCad/share/kicad/library/ir
LibName42=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName43=C:/Program Files/KiCad/share/kicad/library/leds
LibName44=C:/Program Files/KiCad/share/kicad/library/LEM
LibName45=C:/Program Files/KiCad/share/kicad/library/linear
LibName46=C:/Program Files/KiCad/share/kicad/library/logic_programmable
LibName47=C:/Program Files/KiCad/share/kicad/library/maxim
LibName48=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName49=C:/Program Files/KiCad/share/kicad/library/memory
LibName50=C:/Program Files/KiCad/share/kicad/library/microchip
LibName51=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName52=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName53=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName54=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName55=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName56=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName57=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName58=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName59=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName60=C:/Program Files/KiCad/share/kicad/library/motorola
LibName61=C:/Program Files/KiCad/share/kicad/library/motors
LibName62=C:/Program Files/KiCad/share/kicad/library/msp430
LibName63=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName64=C:/Program Files/KiCad/share/kicad/library/nxp
LibName65=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName66=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName67=C:/Program Files/KiCad/share/kicad/library/opto
LibName68=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName69=C:/Program Files/KiCad/share/kicad/library/philips
LibName70=C:/Program Files/KiCad/share/kicad/library/power
LibName71=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName72=C:/Program Files/KiCad/share/kicad/library/powerint
LibName73=C:/Program Files/KiCad/share/kicad/library/pspice
LibName74=C:/Program Files/KiCad/share/kicad/library/references
LibName75=C:/Program Files/KiCad/share/kicad/library/regul
LibName76=C:/Program Files/KiCad/share/kicad/library/relays
LibName77=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName78=C:/Program Files/KiCad/share/kicad/library/RFSolutions
LibName79=C:/Program Files/KiCad/share/kicad/library/sensors
LibName80=C:/Program Files/KiCad/share/kicad/library/silabs
LibName81=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName82=C:/Program Files/KiCad/share/kicad/library/stm8
LibName83=C:/Program Files/KiCad/share/kicad/library/stm32
LibName84=C:/Program Files/KiCad/share/kicad/library/supertex
LibName85=C:/Program Files/KiCad/share/kicad/library/switches
LibName86=C:/Program Files/KiCad/share/kicad/library/texas
LibName87=C:/Program Files/KiCad/share/kicad/library/transf
LibName88=C:/Program Files/KiCad/share/kicad/library/transistors
LibName89=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName90=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName91=C:/Program Files/KiCad/share/kicad/library/valves
LibName92=C:/Program Files/KiCad/share/kicad/library/video
LibName93=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName94=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName95=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName96=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName97=C:/Program Files/KiCad/share/kicad/library/zetex
LibName98=C:/Program Files/KiCad/share/kicad/library/Zilog
LibName99=D:/GitHub/DIY-Multiprotocol-TX-Module/PCB v2.3d/Multipro-txV2-3d-cache
[general]
version=1
